### ISSUE TITLE
报错了今天

### ISSUE THREAD

**Issue by bnnpyhk** [cutecutecat/KnightReport#1]
识别不了url了

**Comment by cutecutecat** [comment]
建议贴上报错信息`KnightReport.err`和`KnightReport.log`

**Comment by bnnpyhk** [comment]
Traceback (most recent call last):
File "main.py", line 22, in
File "ctrl.py", line 47, in exec
File "utils.py", line 74, in marshal
File "utils.py", line 74, in
File "utils.py", line 34, in to_list
File "utils.py", line 34, in
KeyError: 1

这个错误

**Comment by cutecutecat** [comment]
和[这里](https://github.com/cutecutecat/KnightReport/issues/3)是同样的问题，我会优先来处理

**Comment by cutecutecat** [comment]
已经完成，目前应该可以针对这些错误正常输出报表，可以尝试下载1.1.1版本。

但是需要注意的是，问题并没有结束，如果数据本身还是有问题，可能会出现显示错误，比如说某人某天的漏刀数量显示为1。如果遇到这种情况，可以开新的issue让我看看log的结果，看看能不能彻底修复。
