### ISSUE TITLE
[BUG]并未生成报表

### ISSUE THREAD

**Issue by Mashiro-qwq** [cutecutecat/KnightReport#12]
软件版本:0.9

我使用的Chrome是canany版,并未正确识别到,成功打开edge浏览器,网页数据一切正常,但并未生成报表(静默等待5分钟)

日志:
KnightReport.log
```
2021-11-16 22:23:24,705 - main.py[line:23] - INFO: 坎公骑冠剑————超级骑士报表————v0.9
2021-11-16 22:23:24,705 - main.py[line:24] - INFO: by [ NGA | bigfun | TapTap ]@星星星痕
2021-11-16 22:23:24,705 - main.py[line:25] - INFO: 如有疑问或建议可以到https://github.com/cutecutecat/KnightReport提交issue
2021-11-16 22:23:24,705 - browser\intro.py[line:9] - INFO: 开始尝试，获得用户cookies
2021-11-16 22:23:26,889 - browser\method_auto.py[line:42] - WARNING: 尝试启动chrome浏览器失败
2021-11-16 22:23:26,890 - browser\method_auto.py[line:39] - INFO: 成功启动edge浏览器
```

KnightReport.err.log
```
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bigfun.cn', port=443): Max retries exceeded with url: /api/feweb?target=kan-gong-guild-log-filter%2Fa (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "browser\intro.py", line 21, in initBrowser
  File "browser\method_auto.py", line 62, in fetch_cookies
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.bigfun.cn', port=443): Max retries exceeded with url: /api/feweb?target=kan-gong-guild-log-filter%2Fa (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

```

**Comment by Mashiro-qwq** [comment]
咳..补充一下,关掉代理软件可以正常生成了...请修复它

**Comment by Mashiro-qwq** [comment]
![image](https://user-images.githubusercontent.com/46055880/142004306-9be80c6f-b3c7-4fb6-af3a-895f2b217ed5.png)
另外评价一下现在的版本,宋体不如等线字体观感清晰,有很明显的锯齿感

且希望能增加居中功能(虽然不加也可以,就是后期进一步处理表格数据还需要多一道工作)
![image](https://user-images.githubusercontent.com/46055880/142004803-11fbf304-1b69-458d-90c6-d8a249282560.png)

**Comment by cutecutecat** [comment]
代理的问题我之前关注过，的确存在很久了，但是不好处理
问题核心在于https://github.com/psf/requests/issues/5740#issuecomment-774392734
简单来说，Python内部库urllib，对于http类型的代理，会错误识别成https类型的，造成数据包投递失败。
这是一个底层问题，追踪在这里https://bugs.python.org/issue42627 目前还没有解决

我之前构思过这样几种方式：
1. 强制本程序不走任何代理，但这样如果遇到必须要代理才能访问b站API时会很僵
2. 重写urllib返回的https代理为http，但是万一用户用的就是https代理，就会南辕北辙

考虑到上面那个问题追踪已经有pr了，只是没合并，我就摸了，等更新之后我这边同步更新~

**Comment by cutecutecat** [comment]
有关格式的问题，我本周末来研究下API，应该都能处理掉

**Comment by cutecutecat** [comment]
有关canany版的chrome无法启动的问题，之前查询过资料在不同系统中Chrome的安装路径会有轻微区别。
为了兼容性，我没有硬指定可执行文件路径，尝试的启动方式为在 powershell中输入`start chrome`的方案，对我装的稳定版是可以用的~
接下来有时间我会多装几个版本来测试

**Comment by Mashiro-qwq** [comment]
> ~有关canany版的chrome无法启动的问题，之前查询过资料在不同系统中Chrome的安装路径会有轻微区别。 为了兼容性，我没有硬指定可执行文件路径，尝试的启动方式为在 powershell中输入`start chrome`的方案，对我装的稳定版是可以用的~ 接下来有时间我会多装几个版本来测试~
> 
> ~测完了，已经复现，这是高优先级问题，马上来修~ 已经解决~

非常感谢!静候后续更新
